import os
rpt = "/Users/macbook/FnB-Container-Caffe/plans/250803-0019-saas-pivot-bootstrap/reports"
os.makedirs(rpt, exist_ok=True)
routes = [
    ("admin-audit-logs.ts", 212, "Audit log viewer"),
    ("admin-loyalty.ts", 160, "Admin loyalty management"),
    ("admin-metrics.ts", 110, "Admin metrics dashboard"),
    ("admin-qr.ts", 188, "Admin QR generation"),
    ("admin-sales.ts", 153, "Admin sales reports"),
    ("analytics-hono.ts", 292, "Analytics endpoints"),
    ("auth.ts", 18, "Auth routing"),
    ("birthday.ts", 141, "Birthday rewards"),
    ("broadcast.ts", 224, "Broadcast messaging"),
    ("cal-booking-webhook.ts", 212, "Cal.com booking webhook"),
    ("campaigns.ts", 265, "Marketing campaigns"),
    ("categories.ts", 76, "Menu categories CRUD"),
    ("chat.ts", 141, "Chat/messaging"),
    ("checkin.ts", 139, "Customer check-in"),
    ("contact.ts", 77, "Contact form"),
    ("cron.ts", 217, "Scheduled cron jobs"),
    ("customers.ts", 226, "Customer management"),
    ("dindin.ts", 361, "DinDin integration"),
    ("erpnext-invoices.ts", 138, "ERPNext invoices"),
    ("erpnext-pos.ts", 144, "ERPNext POS"),
    ("erpnext-sync.ts", 131, "ERPNext sync"),
    ("erpnext.ts", 197, "ERPNext integration"),
    ("health.ts", 38, "Health check"),
    ("kds-mobile.ts", 86, "KDS mobile"),
    ("loyalty.ts", 164, "Loyalty program"),
    ("mautic-bridge.ts", 12, "Mautic bridge"),
    ("menu.ts", 109, "Menu endpoints"),
    ("mixpost.ts", 203, "Mixpost/social"),
    ("notifications-mobile.ts", 167, "Mobile notifications"),
    ("order-stream.ts", 176, "Order stream"),
    ("orders-hono.ts", 372, "Orders Hono sub-router"),
    ("orders.ts", 13, "Orders routing stub"),
    ("orders-mobile.ts", 132, "Mobile orders"),
    ("payments.ts", 263, "Payments/refunds"),
    ("pretix.ts", 215, "Pretix ticketing"),
    ("products.ts", 94, "Products CRUD"),
    ("promotions.ts", 260, "Promotions management"),
    ("push.ts", 76, "Push notifications"),
    ("realtime-orders.ts", 38, "Realtime orders"),
    ("referrals.ts", 195, "Referral program"),
    ("refunds.ts", 253, "Refunds"),
    ("reports.ts", 413, "Reports generation"),
    ("reservations.ts", 138, "Reservations"),
    ("reviews.ts", 95, "Reviews"),
    ("shifts.ts", 120, "Staff shifts"),
    ("signage.ts", 119, "Digital signage"),
    ("staff-auth.ts", 270, "Staff authentication"),
    ("subscriptions.ts", 40, "Subscriptions"),
    ("tables-mobile.ts", 75, "Mobile tables"),
    ("tables.ts", 204, "Table management"),
    ("version.ts", 21, "Version endpoint"),
    ("vitals.ts", 66, "Health vitals"),
    ("webhooks.ts", 215, "Webhooks handler"),
    ("zalo.ts", 72, "Zalo integration"),
]
