// ESLint Flat Config - ESLint v9+
// https://eslint.org/docs/latest/use/configure/migration-guide

import typescriptParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';

export default [
  // Global ignores must be in a standalone object without other keys
  {
    ignores: [
      'node_modules/**',
      '*.min.js',
      'coverage/**',
      'public/*.min.js',
      'js/*.min.js',
      'dashboard/*.min.js',
      'worker/src/**/*.js',
      'worker/src/**/__tests__/**',
      'worker/src/**/*.test.ts',
      'packages/**/__tests__/**',
      'packages/**/*.test.ts',
      'tests/**',
    ],
  },
  // JS files
  {
    files: ['**/*.js', '**/*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        CustomEvent: 'readonly',
        EventTarget: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        cancelAnimationFrame: 'readonly',
        FormData: 'readonly',
        WebSocket: 'readonly',
        IntersectionObserver: 'readonly',
        requestAnimationFrame: 'readonly',
        performance: 'readonly',
        Image: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
        self: 'readonly',
        caches: 'readonly',
        clients: 'readonly',
        crypto: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        showToast: 'readonly',
        AURA_DEBUG: 'readonly',
        gsap: 'readonly',
      },
    },
    rules: {
      'indent': ['warn'],
      'linebreak-style': ['error', 'unix'],
      'quotes': ['error', 'single'],
      'semi': ['error', 'always'],
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-console': 'warn',
      'no-debugger': 'warn',
      'no-var': 'error',
      'prefer-const': 'error',
      'no-undef': 'error',
      'no-implicit-globals': 'error',
      'no-multi-spaces': 'error',
      'no-trailing-spaces': 'error',
      'eol-last': 'error',
      'eqeqeq': ['error', 'always', { null: 'ignore' }],
      'curly': 'error',
      'dot-notation': 'warn',
      'no-unused-expressions': 'warn',
      'no-shadow': 'warn',
      'no-throw-literal': 'error',
      'no-return-assign': 'error',
      'no-useless-return': 'warn',
      'array-callback-return': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-script-url': 'error',
      'no-caller': 'error',
      'no-void': 'error',
      'prefer-promise-reject-errors': 'error',
    },
  },
  // TypeScript for worker/src/**/*.ts
  {
    files: ['worker/src/**/*.ts'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    linterOptions: {
      reportUnusedDisableDirectives: 'off',
    },
    rules: {
      indent: 'off',
      curly: 'off',
      'no-var': 'off',
      'prefer-const': 'off',
      'no-undef': 'off',
      'no-void': 'off',
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
      'no-shadow': 'off',
      '@typescript-eslint/no-shadow': 'off',
    },
  },
];
