with open('src/components/stitch/StitchAbout.tsx', 'r') as f:
    lines = f.readlines()

# Find insertion point: before "/* ─── Main Component ─── */"
insert_idx = None
for i, line in enumerate(lines):
    if 'Main Component' in line and '─' in line:
        insert_idx = i
        break

if insert_idx is None:
    print("ERROR: Could not find insertion point")
    exit(1)

new_lines = [
    '\n',
    'function HeaderNav() {\n',
    '  const scrollToOrder = useCallback(() => {\n',
    '    const el = document.getElementById("order-section");\n',
    '    el?.scrollIntoView({ behavior: "smooth" });\n',
    '  }, []);\n',
    '\n',
    '  const navLinks = [\n',
    '    { label: "Home", href: "/" },\n',
    '    { label: "Order", href: "#order-section" },\n',
    '    { label: "Events", href: "#events" },\n',
    '    { label: "About", href: "#about", active: true },\n',
    '    { label: "Contact", href: "#contact" },\n',
    '  ];\n',
    '\n',
    '  return (\n',
    '    <header\n',
    '      className="fixed top-0 left-0 right-0 z-50 h-16"\n',
    '      style={{\n',
    '        backgroundColor: "rgba(10, 26, 46, 0.85)",\n',
    '        backdropFilter: "blur(20px)",\n',
    '        WebkitBackdropFilter: "blur(20px)",\n',
    '        borderBottom: "1px solid var(--aura-border-muted, rgba(168, 169, 173, 0.1))",\n',
    '      }}\n',
    '    >\n',
    '      <div\n',
    '        className="mx-auto flex h-full max-w-[1280px] items-center justify-between px-[var(--aura-container-padding,24px)]"\n',
    '      >\n',
    '        <a\n',
    '          href="/"\n',
    '          className="text-xl font-bold uppercase tracking-wider"\n',
    '          style={{\n',
    '            color: "#f2c08d",\n',
    "            fontFamily: 'var(--aura-font-display, \"Libre Caslon Text\", Georgia, serif)',\n",
    "          }}\n",
    '        >\n',
    '          AURA CAFE\n',
    '        </a>\n',
    '        <nav className="hidden items-center gap-8 md:flex">\n',
    '          {navLinks.map((link) => (\n',
    '            <a\n',
    '              key={link.label}\n',
    '              href={link.href}\n',
    '              className={clsx(\n',
    '                "text-sm transition-colors duration-200",\n',
    '                link.active ? "font-semibold" : "hover:text-[#f2c08d]",\n',
    '              )}\n',
    '              style={{\n',
    '                color: link.active ? "#f2c08d" : "var(--aura-text-secondary, #a0a8b0)",\n',
    '              }}\n',
    '            >\n',
    '              {link.label}\n',
    '            </a>\n',
    '          ))}\n',
    '        </nav>\n',
    '        <button\n',
    '          type="button"\n',
    '          onClick={scrollToOrder}\n',
    '          className="rounded px-6 py-2 text-sm font-semibold uppercase tracking-wider transition-all hover:opacity-90"\n',
    '          style={{\n',
    '            backgroundColor: "var(--aura-tertiary, #d4a574)",\n',
    '            color: "var(--aura-noir-void, #0A1A2E)",\n',
    '          }}\n',
    '        >\n',
    '          Order Now\n',
    '        </button>\n',
    '      </div>\n',
    '    </header>\n',
    '  );\n',
    '}\n',
    '\n',
    'function TeamSection() {\n',
    '  const team = [\n',
    '    {\n',
    '      name: "Nguyen Van Minh",\n',
    '      role: "Founder & Head Roaster",\n',
    '      desc: "15+ years in specialty coffee. Curates every bean lot and roast profile.",\n',
    '    },\n',
    '    {\n',
    '      name: "Tran Thi Lan",\n',
    '      role: "Operations Director",\n',
    '      desc: "Ensures seamless service across all 5 container zones, from Jade Counter to VIP Steel Nest.",\n',
    '    },\n',
    '    {\n',
    '      name: "Le Hoang Duc",\n',
    '      role: "Creative & Brand Lead",\n',
    '      desc: "Industrial-design-first brand identity — every pixel, every container joint.",\n',
    '    },\n',
    '    {\n',
    '      name: "Pham Quoc Bao",\n',
    '      role: "Tech & Systems Architect",\n',
    '      desc: "QR ordering, POS integrations, and the digital ecosystem that runs AURA.",\n',
    '    },\n',
    '  ];\n',
    '\n',
    '  return (\n',
    '    <section\n',
    '      className="px-[var(--aura-container-padding,24px)] py-24 md:py-32"\n',
    '      style={{ backgroundColor: "var(--aura-bg-surface, #0d1b2a)" }}\n',
    '    >\n',
    '      <div className="mx-auto max-w-[1280px]">\n',
    '        <div className="mb-16 text-center md:mb-24">\n',
    '          <h2\n',
    '            className="mb-4 text-4xl md:text-5xl"\n',
    '            style={{\n',
    '              color: "var(--aura-text-primary, #e8e8e8)",\n',
    '              fontFamily: \'var(--aura-font-display, "Libre Caslon Text", Georgia, serif)\',\n',
    '            }}\n',
    '          >\n',
    '            The Minds Behind the Machine\n',
    '          </h2>\n',
    '          <p\n',
    '            className="mx-auto max-w-xl font-light leading-relaxed"\n',
    '            style={{ color: "var(--aura-text-secondary, #a0a8b0)" }}\n',
    '          >\n',
    '            Four specialists. One obsession — making AURA CAFE the most precise nocturnal experience in the Mekong Delta.\n',
    '          </p>\n',
    '        </div>\n',
    '        <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4">\n',
    '          {team.map((member) => (\n',
    '            <div\n',
    '              key={member.name}\n',
    '              className="glass-card-about flex flex-col items-center p-8 text-center"\n',
    '            >\n',
    '              <div\n',
    '                className="mb-6 flex h-20 w-20 items-center justify-center rounded-full"\n',
    '                style={{\n',
    '                  backgroundColor: "var(--aura-bg-elevated, #162a3d)",\n',
    '                  border: "1px solid var(--aura-border-muted, rgba(168, 169, 173, 0.2))",\n',
    '                }}\n',
    '              >\n',
    '                <Users className="h-8 w-8" style={{ color: "var(--aura-tertiary, #d4a574)" }} />\n',
    '              </div>\n',
    '              <h3\n',
    '                className="mb-1 text-lg font-semibold text-white"\n',
    '                style={{ fontFamily: \'var(--aura-font-body, "Space Grotesk", system-ui, sans-serif)\' }}\n',
    '              >\n',
    '                {member.name}\n',
    '              </h3>\n',
    '              <span\n',
    '                className="mb-3 text-xs font-bold uppercase tracking-widest"\n',
    '                style={{ color: "var(--aura-tertiary, #d4a574)" }}\n',
    '              >\n',
    '                {member.role}\n',
    '              </span>\n',
    '              <p\n',
    '                className="text-sm leading-relaxed"\n',
    '                style={{ color: "var(--aura-text-secondary, #a0a8b0)" }}\n',
    '              >\n',
    '                {member.desc}\n',
    '              </p>\n',
    '            </div>\n',
    '          ))}\n',
    '        </div>\n',
    '      </div>\n',
    '    </section>\n',
    '  );\n',
    '}\n',
    '\n',
]

for nl in reversed(new_lines):
    lines.insert(insert_idx, nl)

with open('src/components/stitch/StitchAbout.tsx', 'w') as f:
    f.writelines(lines)

print(f"Inserted {len(new_lines)} lines at line {insert_idx}. Total: {len(lines)}")
