import type { MenuItemData } from './StitchMenuNew-types';

/**
 * Toàn bộ thực đơn AURA CAFE — Sa Đéc, Đồng Tháp
 * Nguồn: menu thực tế của quán (bảng giá tháng 9/2026)
 * Ảnh sản phẩm: AI Generated chuyên nghiệp chuẩn Concept Cafe Container AURA
 */
export const DEFAULT_ITEMS: MenuItemData[] = [

  /* ─── CÀ PHÊ TRUYỀN THỐNG ────────────────────────────────── */
  {
    id: 'tc001',
    name: 'Cà phê máy / phin truyền thống',
    description: 'Cà phê đen nguyên chất pha máy espresso hoặc phin truyền thống, phục vụ đá hoặc nóng.',
    price: '20.000₫',
    imageSrc: '/menu/ca-phe-den.jpg',
    imageAlt: 'Cà phê đen nguyên chất pha phin / máy',
    category: 'traditional-coffee',
    badge: 'TRUYỀN THỐNG',
  },
  {
    id: 'tc002',
    name: 'Cà phê sữa máy / phin',
    description: 'Cà phê đậm đà kết hợp sữa đặc béo ngậy, pha máy hoặc phin. Phục vụ đá hoặc nóng.',
    price: '25.000₫',
    imageSrc: '/menu/ca-phe-sua.jpg',
    imageAlt: 'Cà phê sữa đá / nóng pha phin chuẩn gu Việt',
    category: 'traditional-coffee',
    badge: 'BÁN CHẠY',
  },
  {
    id: 'tc003',
    name: 'Cà phê / Matcha muối',
    description: 'Lớp kem muối béo mịn phủ lên cà phê hoặc matcha thơm lừng — đặc sản được yêu thích nhất.',
    price: '28.000₫',
    imageSrc: '/menu/ca-phe-muoi.jpg',
    imageAlt: 'Cà phê muối / Matcha muối AURA CAFE',
    category: 'traditional-coffee',
    badge: 'ĐẶC SẢN',
  },
  {
    id: 'tc004',
    name: 'Bạc xỉu đá / nóng',
    description: 'Vị ngọt dịu thơm béo từ sữa tươi và sữa đặc, thoảng nhẹ hương cà phê tinh tế.',
    price: '28.000₫',
    imageSrc: '/menu/bac-xiu.jpg',
    imageAlt: 'Bạc xỉu đá 3 tầng thơm béo',
    category: 'traditional-coffee',
  },
  {
    id: 'tc005',
    name: 'Ca cao đá / nóng',
    description: 'Nguyên chất ca cao mộc mạc, vị đắng nhẹ hòa quyện ngọt bùi. Thức uống giải nhiệt chuẩn vị.',
    price: '20.000₫',
    imageSrc: '/menu/ca-phe-den.jpg',
    imageAlt: 'Ca cao đá hoặc nóng',
    category: 'traditional-coffee',
  },
  {
    id: 'tc006',
    name: 'Ca cao sữa đá / nóng',
    description: 'Ca cao pha sữa đặc béo ngậy, cân bằng hoàn hảo giữa ngọt và đắng nhẹ.',
    price: '30.000₫',
    imageSrc: '/menu/ca-phe-sua.jpg',
    imageAlt: 'Ca cao sữa đá hoặc nóng',
    category: 'traditional-coffee',
  },
  {
    id: 'tc007',
    name: 'Matcha latte đá',
    description: 'Bột trà xanh Nhật Bản thượng hạng pha cùng sữa tươi mát lạnh, màu xanh ngọc bắt mắt.',
    price: '25.000₫',
    imageSrc: '/menu/matcha-latte.jpg',
    imageAlt: 'Matcha latte đá phân tầng',
    category: 'traditional-coffee',
  },

  /* ─── CÀ PHÊ NÓNG ──────────────────────────────────────── */
  {
    id: 'hc001',
    name: 'Espresso',
    description: 'Cà phê kiểu Ý — một shot espresso đậm đặc, crema vàng óng, thơm hậu vị dài.',
    price: '20.000₫',
    imageSrc: '/menu/ca-phe-den.jpg',
    imageAlt: 'Cà phê Espresso',
    category: 'hot-coffee',
  },
  {
    id: 'hc002',
    name: 'Americano',
    description: 'Cà phê kiểu Mỹ — espresso pha loãng với nước nóng, nhẹ dịu và thơm thanh.',
    price: '25.000₫',
    imageSrc: '/menu/ca-phe-den.jpg',
    imageAlt: 'Cà phê Americano',
    category: 'hot-coffee',
  },
  {
    id: 'hc003',
    name: 'Cappuccino',
    description: 'Cà phê bọt sữa kiểu Ý — espresso phủ lớp bọt sữa dày mịn như nhung, rắc nhẹ bột ca cao.',
    price: '35.000₫',
    imageSrc: '/menu/cappuccino.jpg',
    imageAlt: 'Cà phê Cappuccino tạo hình nghệ thuật',
    category: 'hot-coffee',
    badge: 'SIGNATURE',
  },
  {
    id: 'hc004',
    name: 'Mocha',
    description: 'Cà phê và socola — espresso hòa quyện siro sô-cô-la đắng ngọt và sữa tươi nóng.',
    price: '35.000₫',
    imageSrc: '/menu/cappuccino.jpg',
    imageAlt: 'Cà phê Mocha nóng thơm lừng',
    category: 'hot-coffee',
  },
  {
    id: 'hc005',
    name: 'Latte',
    description: 'Cà phê sữa nóng kiểu Ý — espresso nhẹ nhàng trong lớp sữa nóng mịn, thích hợp buổi sáng.',
    price: '35.000₫',
    imageSrc: '/menu/cappuccino.jpg',
    imageAlt: 'Cà phê Latte nóng',
    category: 'hot-coffee',
  },
  {
    id: 'hc006',
    name: 'Greentea Latte nóng',
    description: 'Trà xanh sữa nóng — matcha hòa tan trong sữa tươi nóng, thanh mát và nhẹ nhàng.',
    price: '35.000₫',
    imageSrc: '/menu/matcha-latte.jpg',
    imageAlt: 'Trà xanh sữa nóng Greentea Latte',
    category: 'hot-coffee',
  },

  /* ─── ĐÁ XAY (FRAPPUCCINO) ─────────────────────────────── */
  {
    id: 'fp001',
    name: 'Coffee Frappuccino',
    description: 'Cà phê đá xay mịn, mát lạnh sảng khoái với lớp whipped cream béo thơm bên trên.',
    price: '35.000₫',
    imageSrc: '/menu/frappuccino.jpg',
    imageAlt: 'Cà phê đá xay Frappuccino kem tươi',
    category: 'frappuccino',
  },
  {
    id: 'fp002',
    name: 'Cookie Frappuccino',
    description: 'Cà phê bánh xay — vị cookies & cream ngọt ngào hòa quyện cùng cà phê đá xay mát lạnh.',
    price: '35.000₫',
    imageSrc: '/menu/frappuccino.jpg',
    imageAlt: 'Cookie Frappuccino đá xay',
    category: 'frappuccino',
  },
  {
    id: 'fp003',
    name: 'Mocha Frappuccino',
    description: 'Cà phê socola đá xay — sự kết hợp giữa sô-cô-la đắng ngọt và cà phê lạnh sánh mịn.',
    price: '35.000₫',
    imageSrc: '/menu/frappuccino.jpg',
    imageAlt: 'Mocha Frappuccino đá xay',
    category: 'frappuccino',
  },
  {
    id: 'fp004',
    name: 'Coconut Blueberry Coffee Ice',
    description: 'Cà phê dừa Việt quốc — cà phê dừa béo thơm quyện vị việt quất chua ngọt tươi mát. Món signature độc bản.',
    price: '35.000₫',
    imageSrc: '/menu/frappuccino.jpg',
    imageAlt: 'Cà phê dừa Việt quốc đá xay',
    category: 'frappuccino',
    badge: 'SIGNATURE',
  },
  {
    id: 'fp005',
    name: 'Blueberry Yogurt Frappuccino',
    description: 'Sữa chua Việt quốc bánh xay — sữa chua mịn quyện việt quất tươi và bánh xay lạnh, chua ngọt hài hòa.',
    price: '35.000₫',
    imageSrc: '/menu/yaourt.jpg',
    imageAlt: 'Blueberry Yogurt Frappuccino đá xay',
    category: 'frappuccino',
  },
  {
    id: 'fp006',
    name: 'Matcha Frappuccino',
    description: 'Trà xanh đá xay — matcha cao cấp xay lạnh sánh mịn với sữa tươi, thanh mát và bắt mắt.',
    price: '35.000₫',
    imageSrc: '/menu/matcha-latte.jpg',
    imageAlt: 'Trà xanh Matcha đá xay',
    category: 'frappuccino',
  },

  /* ─── SODA KIỂU Ý ───────────────────────────────────────── */
  {
    id: 'sd001',
    name: 'Sapphire — Blue Curacao',
    description: 'Soda xanh biển đại dương rực rỡ, vị cam thơm sảng khoái và gas mát lạnh sảng khoái.',
    price: '25.000₫',
    imageSrc: '/menu/soda-blue.jpg',
    imageAlt: 'Soda Sapphire Blue Curacao mát lạnh sảng khoái',
    category: 'soda',
    badge: 'PHỔ BIẾN',
  },
  {
    id: 'sd002',
    name: 'Emerald — Bạc Hà',
    description: 'Soda xanh lá mát lạnh với vị bạc hà the mát, giải nhiệt tức thì trong ngày hè Sa Đéc.',
    price: '25.000₫',
    imageSrc: '/menu/soda-blue.jpg',
    imageAlt: 'Soda Emerald Bạc Hà',
    category: 'soda',
  },

  /* ─── TRÀ (TEA) ─────────────────────────────────────────── */
  {
    id: 'te001',
    name: 'Lipton chanh đá / nóng',
    description: 'Trà Lipton vàng pha chanh tươi chua thanh, uống đá hoặc nóng đều sảng khoái.',
    price: '18.000₫',
    imageSrc: '/menu/tra-dao.jpg',
    imageAlt: 'Trà Lipton chanh đá hoặc nóng',
    category: 'tea',
  },
  {
    id: 'te002',
    name: 'Lipton sữa đá / nóng',
    description: 'Trà Lipton pha sữa đặc béo ngậy, hương trà thơm dịu hòa cùng vị sữa tươi thanh.',
    price: '25.000₫',
    imageSrc: '/menu/tra-dao.jpg',
    imageAlt: 'Trà sữa Lipton đá hoặc nóng',
    category: 'tea',
  },
  {
    id: 'te003',
    name: 'Lipton cam đá / nóng',
    description: 'Trà Lipton kết hợp nước cam tươi, vị chua ngọt dễ chịu và giàu vitamin C tự nhiên.',
    price: '25.000₫',
    imageSrc: '/menu/nuoc-cam.jpg',
    imageAlt: 'Trà Lipton cam đá hoặc nóng',
    category: 'tea',
  },
  {
    id: 'te004',
    name: 'Trà cúc thảo mộc đá / nóng',
    description: 'Trà hoa cúc thảo mộc thiên nhiên, thanh mát dịu nhẹ, tốt cho sức khỏe và giảm stress.',
    price: '29.000₫',
    imageSrc: '/menu/binh-tra.jpg',
    imageAlt: 'Trà cúc thảo mộc ấm nóng',
    category: 'tea',
  },
  {
    id: 'te005',
    name: 'Trà mãng cầu',
    description: 'Trà từ lá mãng cầu — đặc sản miền Tây Nam Bộ, vị ngọt tự nhiên, tốt cho hệ tiêu hóa.',
    price: '29.000₫',
    imageSrc: '/menu/tra-dao.jpg',
    imageAlt: 'Trà mãng cầu đặc sản miền Tây',
    category: 'tea',
    badge: 'ĐẶC SẢN',
  },
  {
    id: 'te006',
    name: 'Trà đào',
    description: 'Cốt trà thơm lừng kết hợp miếng đào giòn sần sật và nước cốt đào chua ngọt giải nhiệt.',
    price: '30.000₫',
    imageSrc: '/menu/tra-dao.jpg',
    imageAlt: 'Ly trà đào thanh mát giòn ngọt',
    category: 'tea',
    badge: 'PHỔ BIẾN',
  },

  /* ─── SINH TỐ (SMOOTHIES) ───────────────────────────────── */
  {
    id: 'sm001',
    name: 'Sinh tố Dâu / Bơ / Mãng cầu / Sapo',
    description: 'Sinh tố trái cây tươi chọn lọc — dâu tây, bơ sáp dẻo, mãng cầu hoặc sapodilla. Xay mịn béo ngậy.',
    price: '35.000₫',
    imageSrc: '/menu/sinh-to-bo.jpg',
    imageAlt: 'Sinh tố bơ sáp tươi sánh mịn',
    category: 'smoothies',
    badge: 'BÁN CHẠY',
  },

  /* ─── YAOURT ─────────────────────────────────────────────── */
  {
    id: 'yo001',
    name: 'Yaourt đá',
    description: 'Sữa chua lạnh truyền thống, vị chua ngọt tự nhiên, mát lạnh và giải nhiệt hoàn hảo.',
    price: '20.000₫',
    imageSrc: '/menu/yaourt.jpg',
    imageAlt: 'Yaourt đá mát lạnh',
    category: 'yogurt',
  },
  {
    id: 'yo002',
    name: 'Yaourt cà phê',
    description: 'Sữa chua kết hợp cà phê đậm đà — vị chua ngọt hòa quyện hương cà phê thơm lừng.',
    price: '23.000₫',
    imageSrc: '/menu/yaourt.jpg',
    imageAlt: 'Yaourt cà phê độc đáo',
    category: 'yogurt',
  },
  {
    id: 'yo003',
    name: 'Yaourt Việt Quốc',
    description: 'Sữa chua việt quất Việt Nam — chua ngọt hài hòa, màu tím đẹp mắt và giàu antioxidant.',
    price: '25.000₫',
    imageSrc: '/menu/yaourt.jpg',
    imageAlt: 'Yaourt việt quất Việt Quốc',
    category: 'yogurt',
    badge: 'MỚI',
  },
  {
    id: 'yo004',
    name: 'Yaourt hũ',
    description: 'Sữa chua hũ nguyên chất tự làm — đặc mịn, chua nhẹ và thuần vị truyền thống.',
    price: '15.000₫',
    imageSrc: '/menu/yaourt.jpg',
    imageAlt: 'Yaourt hũ truyền thống',
    category: 'yogurt',
  },

  /* ─── NƯỚC ÉP ───────────────────────────────────────────── */
  {
    id: 'jc001',
    name: 'Đá chanh',
    description: 'Nước chanh tươi vắt pha đá, thêm chút muối và đường — thức uống giải khát kinh điển mùa hè.',
    price: '18.000₫',
    imageSrc: '/menu/nuoc-cam.jpg',
    imageAlt: 'Nước đá chanh tươi',
    category: 'juice',
  },
  {
    id: 'jc002',
    name: 'Rau má',
    description: '100% rau má sạch xay tươi tại chỗ, giải nhiệt, thanh mát và tốt cho sức khỏe.',
    price: '18.000₫',
    imageSrc: '/menu/rau-ma.jpg',
    imageAlt: 'Nước rau má xay tươi nguyên chất',
    category: 'juice',
    badge: 'HEALTHY',
  },
  {
    id: 'jc003',
    name: 'Rau má dừa / sữa',
    description: 'Rau má xay kết hợp nước dừa tươi hoặc sữa tươi — béo mượt và giải nhiệt tức thì.',
    price: '25.000₫',
    imageSrc: '/menu/rau-ma.jpg',
    imageAlt: 'Rau má dừa hoặc sữa tươi',
    category: 'juice',
  },
  {
    id: 'jc004',
    name: 'Dừa trái',
    description: 'Nước dừa xiêm tươi nguyên quả, ngọt thanh tự nhiên và đầy điện giải bổ dưỡng.',
    price: '23.000₫',
    imageSrc: '/menu/nuoc-cam.jpg',
    imageAlt: 'Nước dừa trái tươi',
    category: 'juice',
  },
  {
    id: 'jc005',
    name: 'Dừa đá',
    description: 'Nước dừa tươi pha đá xay mịn, ngọt thanh mát lạnh sảng khoái trong ngày nắng nóng.',
    price: '25.000₫',
    imageSrc: '/menu/nuoc-cam.jpg',
    imageAlt: 'Nước dừa đá mát lạnh',
    category: 'juice',
  },
  {
    id: 'jc006',
    name: 'Cam vắt',
    description: '100% cam sành miền Tây vắt tươi tại chỗ, giữ trọn vẹn vitamin C tự nhiên.',
    price: '23.000₫',
    imageSrc: '/menu/nuoc-cam.jpg',
    imageAlt: 'Nước cam sành vắt tươi nguyên chất',
    category: 'juice',
  },

  /* ─── THỨC UỐNG KHÁC ────────────────────────────────────── */
  {
    id: 'od001',
    name: 'Trà đường',
    description: 'Trà mộc pha đường thanh, đơn giản và giải khát. Uống miễn phí tại quầy.',
    price: '18.000₫',
    imageSrc: '/menu/tra-dao.jpg',
    imageAlt: 'Trà đường giải nhiệt',
    category: 'other-drinks',
  },
  {
    id: 'od002',
    name: 'Bình trà bắc',
    description: 'Bình trà xanh miền Bắc truyền thống, uống vừa miệng, phù hợp ngồi lâu tại quán.',
    price: '15.000₫',
    imageSrc: '/menu/binh-tra.jpg',
    imageAlt: 'Bình trà bắc truyền thống',
    category: 'other-drinks',
  },
  {
    id: 'od003',
    name: 'Đá me',
    description: 'Nước me chua ngọt đặc trưng miền Tây, pha đá lạnh thanh mát, rắc đậu phộng rang giòn thơm.',
    price: '18.000₫',
    imageSrc: '/menu/da-me.jpg',
    imageAlt: 'Nước đá me đậu phộng rang',
    category: 'other-drinks',
    badge: 'ĐỊA PHƯƠNG',
  },
  {
    id: 'od004',
    name: 'Chanh muối',
    description: 'Chanh muối ngâm truyền thống — vị chua mặn ngọt cân bằng, giải nhiệt và kích thích vị giác.',
    price: '18.000₫',
    imageSrc: '/menu/da-me.jpg',
    imageAlt: 'Chanh muối truyền thống',
    category: 'other-drinks',
  },
  {
    id: 'od005',
    name: 'Sữa tươi',
    description: 'Sữa tươi nguyên chất, uống lạnh hoặc nóng theo sở thích. Bổ dưỡng và đơn giản.',
    price: '20.000₫',
    imageSrc: '/menu/bac-xiu.jpg',
    imageAlt: 'Sữa tươi nguyên chất',
    category: 'other-drinks',
  },

  /* ─── GIẢI KHÁT ĐÓNG CHAI ───────────────────────────────── */
  {
    id: 'bt001',
    name: 'Nước suối',
    description: 'Nước khoáng thiên nhiên tinh khiết, đóng chai ướp lạnh. Giải khát nhanh chóng.',
    price: '10.000₫',
    imageSrc: '/menu/dong-chai.jpg',
    imageAlt: 'Nước suối đóng chai ướp lạnh',
    category: 'bottled',
  },
  {
    id: 'bt002',
    name: 'Sting / Coca / Pepsi / 7UP / Ô long',
    description: 'Nước giải khát đóng chai đa dạng: Sting, Coca-Cola, Pepsi, 7UP hoặc trà Ô Long ướp lạnh.',
    price: '15.000₫',
    imageSrc: '/menu/dong-chai.jpg',
    imageAlt: 'Nước ngọt giải khát đóng chai ướp đá',
    category: 'bottled',
  },
  {
    id: 'bt003',
    name: 'Redbull',
    description: 'Nước tăng lực Redbull lon ướp lạnh — bổ sung năng lượng tức thì cho ngày dài năng động.',
    price: '20.000₫',
    imageSrc: '/menu/dong-chai.jpg',
    imageAlt: 'Redbull lon ướp lạnh',
    category: 'bottled',
  },
];
