import type { MenuItemData } from './StitchMenuNew-types';

export const DEFAULT_ITEMS: MenuItemData[] = [
  {
    id: '1',
    name: 'Midnight Espresso',
    description: 'Triple-shot ristretto using our obsidian blend, served in a pre-chilled chrome-rimmed glass.',
    price: '$6.50',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC_QGdUYMDZ4bshFGGOuDClk1QO2FbSuIAAyiGKyZPvZ2j0P1k9fTsCP1QEePIsP_4_AGSSF0noB-pMgP31tTLK5lONgX7aYWGJD8JHQRi7wtaYWcSgyQSl333QcLPg-K-_ye57vjIvaBaGy3r9C31P5tt4-zKdNIxY7kYFSyJORgVUkCrX9l5qM9cKYf5Uv_pTIYJk1wXo8eDgJDk4EOLpqOpH1Dbx6TLvj2ApS5j240P5kDgcabws484acm24ikkEa3VpDiPAWNo',
    imageAlt: 'Macro photograph of a rich dark espresso shot being pulled into a minimalist glass cup with steam rising against a dark navy industrial background',
    category: 'coffee',
    badge: 'FEATURED',
  },
  {
    id: '2',
    name: 'Chrome Velvet Latte',
    description: 'Infused with active charcoal and Madagascar vanilla, finished with a precise velvet microfoam.',
    price: '$8.00',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuALjkXkK9PvJmhMhQQTpMT1PBUly68XCUmWFe_68ragLLJXSWI7XZbcQp8eoISOj960gbBxXSt1yqhQxTzuqe2z0D2pubqGrxJjapmjy3mZ3T3_vmb3iQKQTOzTKdjEnrzf-KyX9x5XayazvprUnxJ5m8O6GEmWyavZbUaAArbsW5BWwwB-aDj8WaGUVw_KnDCCC_XcbG9VQmn-BCta9TJjY_cqOowGMSZ2b3RPcESMsVgf5--vUhqQkf8t577BnVN-lux8ZPR-4bA',
    imageAlt: 'Silky latte featuring intricate charcoal-colored latte art in a brushed metallic chrome vessel on a dark stone coaster',
    category: 'coffee',
  },
  {
    id: '3',
    name: 'Industrial Cold Brew',
    description: '24-hour slow drip extraction through stainless steel filtration. Intense, clean, and energizing.',
    price: '$7.25',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCyrdmvvc0Z7n8qHuPaerW9_V-RLpkxo1asQBGo2lrzTR1AS1R3Nd_dZ1ZvwjJUxJjDRylrXOYEaMdOXgob8NpAlbulht0fxsLpykQMsimhIENB44M9IFx0OFp16N71Y6yRKi-wvLZCTKDxTXbGPxQrd5snG3IDeFxQFB43Y22vH7t84u9wnLUKSpqmDh0qFMNKe0X-DpOb2iSG0-WLB54k1EPBRzHsn6g7PzaOkohUdHN48UY8VtKTFJAUVtztLNyG8JfSg8OyLf0',
    imageAlt: 'Clear apothecary glass bottle filled with dark cold brew coffee with condensation droplets beside a glass with a single large clear ice sphere',
    category: 'cold-brew',
    badge: 'VEGETARIAN',
  },
  {
    id: '4',
    name: 'Bronze Chai',
    description: 'Hand-ground spices bloomed in local honey, paired with a selection of premium black teas.',
    price: '$6.75',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAfTnFSl0lRavfOjng3uA94TL3rKuQXqtLXgpSV9hgW6GloyXk22c6QL7HDuzZPECrexBDwlvOnZkfXv9-liX4zHLiaYnReBurMC6l6fTUmn5OzJ8odnX79mVvqupVKqN8qiiCGu2zBNG8PNRZF7439vMXyajna9CJR877470iChAjL2TLrvnaJC7Yo4yTVel8VPTj-DnlILPeLDzT-7N_oK5s6vUMyTQsGP5Comu1Pc7KzVviaMdseBfMI95_LrOdF8fJ-xBYTIRw',
    imageAlt: 'Warm bronze-colored spiced chai latte topped with cinnamon and star anise in a matte black ceramic cup with metallic bronze interior rim',
    category: 'tea',
  },
  {
    id: '5',
    name: 'Ceremonial Matcha',
    description: 'Stone-ground ceremonial grade tea from Uji, whisked to perfection with oat milk.',
    price: '$7.50',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCo3Ezdo07YoM0sKYg-Yfrh6ntsqGTJvDLWfbmgtAz4sX8D5CtD_Op74E1PhfSk_5DwhqocqR_68cEfC51f-QGhGvMXOPZybvsZvY5uQweisHu9TIWxKBV4wfCKfngQXvjxVfQvXRncZ8e91L7oZM2Yy_WrieJo3XbNclhpy5PQJQk5tlV7Jkv4O2mygsSYTcWdXw14c2tZq5Jrg1mzOHrOC96aHLaGfvYj6uZIzzfUl4MJIUTZJcy_Cjrb3ZJ_KlGUBnaEOKinryM',
    imageAlt: 'Minimalist presentation of a vibrant green matcha latte in a shallow glass bowl with dark granite textures and chrome accents',
    category: 'signature',
  },
  {
    id: '6',
    name: 'Nitro Tonic',
    description: 'Nitro-infused espresso charged with premium tonic and a hint of botanical citrus.',
    price: '$9.00',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB2hGTvBgNF-yso83PziL85EL-6LOc8S5kmoITQUZfQgJeF0a7VRpJnAwUJTV4kRh5eeHJHdlODJf9XkuqFCmG-emNjmamLKDCu5xgDH0G-OFqv3DJ8FnUj_Dp0Y6sGhEUR_9Ys9h8C_pmNiyeagQuk9I5bZO84yQpFi1rPUBTg-2dIxsxLz8lKKIZY6ezzgeX4nQZb55L22oh8wmuw9HSTjX2c4GwGHqzQlyBKc8ZHN5A9ZmjTfp-nz3JHOUGDshJovxWLGzzQJv4',
    imageAlt: 'Artisanal sparkling cold coffee drink served in a crystal flute with a twist of orange peel and visible carbonation bubbles',
    category: 'cold-brew',
  },
];
