import type { MenuItemData } from './StitchMenuNew-types';

export const DEFAULT_ITEMS: MenuItemData[] = [
  {
    id: '1',
    name: 'Midnight Espresso',
    description: 'Triple-shot ristretto using our obsidian blend, served in a pre-chilled chrome-rimmed glass.',
    price: '$6.50',
    imageSrc: '/photos/IMG_6593.webp',
    imageAlt: 'Macro photograph of a rich dark espresso shot being pulled into a minimalist glass cup with steam rising against a dark navy industrial background',
    category: 'coffee',
    badge: 'FEATURED',
  },
  {
    id: '2',
    name: 'Chrome Velvet Latte',
    description: 'Infused with active charcoal and Madagascar vanilla, finished with a precise velvet microfoam.',
    price: '$8.00',
    imageSrc: '/photos/IMG_6581.webp',
    imageAlt: 'Silky latte featuring intricate charcoal-colored latte art in a brushed metallic chrome vessel on a dark stone coaster',
    category: 'coffee',
  },
  {
    id: '3',
    name: 'Industrial Cold Brew',
    description: '24-hour slow drip extraction through stainless steel filtration. Intense, clean, and energizing.',
    price: '$7.25',
    imageSrc: '/photos/IMG_6554-frame.webp',
    imageAlt: 'Clear apothecary glass bottle filled with dark cold brew coffee with condensation droplets beside a glass with a single large clear ice sphere',
    category: 'cold-brew',
    badge: 'VEGETARIAN',
  },
  {
    id: '4',
    name: 'Bronze Chai',
    description: 'Hand-ground spices bloomed in local honey, paired with a selection of premium black teas.',
    price: '$6.75',
    imageSrc: '/photos/IMG_6555-frame.webp',
    imageAlt: 'Warm bronze-colored spiced chai latte topped with cinnamon and star anise in a matte black ceramic cup with metallic bronze interior rim',
    category: 'tea',
  },
  {
    id: '5',
    name: 'Ceremonial Matcha',
    description: 'Stone-ground ceremonial grade tea from Uji, whisked to perfection with oat milk.',
    price: '$7.50',
    imageSrc: '/photos/IMG_6564.webp',
    imageAlt: 'Minimalist presentation of a vibrant green matcha latte in a shallow glass bowl with dark granite textures and chrome accents',
    category: 'signature',
  },
  {
    id: '6',
    name: 'Nitro Tonic',
    description: 'Nitro-infused espresso charged with premium tonic and a hint of botanical citrus.',
    price: '$9.00',
    imageSrc: '/photos/IMG_6693.webp',
    imageAlt: 'Artisanal sparkling cold coffee drink served in a crystal flute with a twist of orange peel and visible carbonation bubbles',
    category: 'cold-brew',
  },
];
