import { Palette } from 'lucide-react';
import { HelmetHead } from '@/components/seo/HelmetHead';
import { Card, CardBody } from '@/components/ui/card';
import { AuraImage } from '@/components/ui/AuraImage';

const DESIGNS = [
  { name: 'Home Landing', file: 'landing-full.html', img: 'landing-full.webp', desc: 'Trang chủ — hero, stats, menu grid, zones, testimonials' },
  { name: 'Home Alt', file: 'landing-alt.html', img: 'landing-alt.webp', desc: 'Trang chủ — biến thể thứ 2' },
  { name: 'Digital Menu', file: 'aura-cafe-menu.html', img: 'aura-cafe-menu-screenshot.webp', desc: 'Menu số — category tabs, product grid, cart sidebar' },
];

export default function StitchGalleryPage() {
  return (
    <>
      <HelmetHead title="Stitch Designs — AURA CAFE" description="AI-generated UI designs for AURA CAFE" />
      <main className="mx-auto max-w-6xl px-4 py-24">
        <h1 className="font-display text-3xl font-bold mb-2"><Palette className="inline mr-2" size={32} />Stitch AI Designs</h1>
        <p className="text-muted/60 mb-8">UI designs generated by Google Stitch AI</p>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {DESIGNS.map(d => (
            <Card key={d.name}>
              <CardBody>
                <a href={'/stitch-designs/' + d.img} target="_blank" rel="noopener noreferrer">
                  <AuraImage src={'/stitch-designs/' + d.img} alt={d.name} className="w-full rounded-lg mb-3 border border-white/10" />
                </a>
                <h2 className="font-display text-lg font-bold">{d.name}</h2>
                <p className="text-sm text-muted/60 mb-3">{d.desc}</p>
                <a href={'/stitch-designs/' + d.file} target="_blank" rel="noopener noreferrer" className="text-accent text-sm underline underline-offset-2">
                  Xem HTML đầy đủ →
                </a>
              </CardBody>
            </Card>
          ))}
        </div>
      </main>
    </>
  );
}
