import tsParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';

export default [
  {
    files: ['src/**/*.ts', 'src/**/*.tsx'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 2020,
        sourceType: 'module',
      },
      globals: {
        console: 'off',
        process: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        crypto: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        setTimeout: 'readonly',
        performance: 'readonly',
        navigator: 'readonly',
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        MutationObserver: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLFormElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLAudioElement: 'readonly',
        HTMLVideoElement: 'readonly',
        SVGElement: 'readonly',
        DOMParser: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        Event: 'readonly',
        EventTarget: 'readonly',
        CustomEvent: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        TouchEvent: 'readonly',
        WheelEvent: 'readonly',
        DragEvent: 'readonly',
        ClipboardEvent: 'readonly',
        ProgressEvent: 'readonly',
        MessageEvent: 'readonly',
        ErrorEvent: 'readonly',
        Promise: 'readonly',
        Symbol: 'readonly',
        Reflect: 'readonly',
        Proxy: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        ArrayBuffer: 'readonly',
        SharedArrayBuffer: 'readonly',
        DataView: 'readonly',
        Int8Array: 'readonly',
        Uint8Array: 'readonly',
        Uint8ClampedArray: 'readonly',
        Int16Array: 'readonly',
        Uint16Array: 'readonly',
        Int32Array: 'readonly',
        Uint32Array: 'readonly',
        Float32Array: 'readonly',
        Float64Array: 'readonly',
        BigInt: 'readonly',
        BigInt64Array: 'readonly',
        BigUint64Array: 'readonly',
        JSON: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        RegExp: 'readonly',
        Error: 'readonly',
        EvalError: 'readonly',
        RangeError: 'readonly',
        ReferenceError: 'readonly',
        SyntaxError: 'readonly',
        TypeError: 'readonly',
        URIError: 'readonly',
        AggregateError: 'readonly',
        Object: 'readonly',
        Function: 'readonly',
        Boolean: 'readonly',
        Number: 'readonly',
        String: 'readonly',
        Symbol: 'readonly',
        Array: 'readonly',
        ParseError: 'readonly',
        SerializationError: 'readonly',
        DeserializationError: 'readonly',
        ZodError: 'readonly',
        h: 'readonly',
        Fragment: 'readonly',
        jsx: 'readonly',
        jsxs: 'readonly',
        createElement: 'readonly',
        StrictMode: 'readonly',
        Suspense: 'readonly',
        useState: 'readonly',
        useEffect: 'readonly',
        useContext: 'readonly',
        useReducer: 'readonly',
        useCallback: 'readonly',
        useMemo: 'readonly',
        useRef: 'readonly',
        useLayoutEffect: 'readonly',
        useImperativeHandle: 'readonly',
        useDebugValue: 'readonly',
        forwardRef: 'readonly',
        memo: 'readonly',
        lazy: 'readonly',
        createContext: 'readonly',
        createRef: 'readonly',
        isValidElement: 'readonly',
        Children: 'readonly',
        render: 'readonly',
        hydrate: 'readonly',
        createRoot: 'readonly',
        act: 'readonly',
        flushSync: 'readonly',
        unstable_batchedUpdates: 'readonly',
        unstable_renderSubtreeIntoContainer: 'readonly',
        findDOMNode: 'readonly',
        PureComponent: 'readonly',
        Component: 'readonly',
        version: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      ...tsPlugin.configs['recommended'].rules,
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-var-requires': 'error',
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type' }],
      '@typescript-eslint/no-misused-promises': ['error', { checksVoidReturn: false }],
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/prefer-nullish-coalescing': 'error',
      '@typescript-eslint/strict-boolean-expressions': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-call': 'error',
      '@typescript-eslint/no-unsafe-argument': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-unsafe-declaration-merging': 'error',
      '@typescript-eslint/restrict-template-expressions': ['error', { allowAny: false }],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/prefer-readonly': 'error',
      '@typescript-eslint/array-type': ['error', { default: 'generic' }],
      '@typescript-eslint/ban-types': ['error', { extendDefaults: true }],
      '@typescript-eslint/naming-convention': [
        'error',
        { selector: 'variableLike', format: ['camelCase', 'PascalCase', 'UPPER_CASE'] },
        { selector: 'typeLike', format: ['PascalCase'] },
      ],
    },
  },
  {
    files: ['src/__tests__/**/*.ts', '**/*.test.ts', '**/*.spec.ts'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 2020,
        sourceType: 'module',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'no-console': 'off',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    },
  },
  {
    files: ['src/**/*.ts', 'src/**/*.tsx'],
    plugins: {},
    rules: {
      'no-console': 'error',
      'no-unused-expressions': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'no-else-return': 'error',
      'no-useless-concat': 'error',
      'no-useless-return': 'error',
      'no-lone-blocks': 'error',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', ignoreRestSiblings: true }],
      'eqeqeq': ['error', 'always'],
      'curly': ['error', 'all'],
      'brace-style': ['error', '1tbs'],
      'no-multi-spaces': 'error',
      'no-trailing-spaces': 'error',
      'no-whitespace-before-property': 'error',
      'semi': ['error', 'always'],
      'quotes': ['error', 'single'],
      'indent': ['error', 2],
      'comma-dangle': ['error', 'never'],
      'comma-spacing': 'error',
      'comma-style': ['error', 'last'],
      'object-curly-spacing': ['error', 'always'],
      'array-bracket-spacing': ['error', 'never'],
      'space-in-parens': ['error', 'never'],
      'space-before-blocks': 'error',
      'space-before-function-paren': ['error', 'never'],
      'keyword-spacing': 'error',
      'space-infix-ops': 'error',
      'space-unary-ops': 'error',
      'spaced-comment': ['error', 'always'],
      'eol-last': 'error',
      'max-len': ['error', { code: 120, ignoreUrls: true, ignoreComments: true }],
      'no-multiple-empty-lines': ['error', { max: 1 }],
      'no-duplicate-imports': 'error',
      'prefer-template': 'error',
      'template-curly-spacing': ['error', 'never'],
      'key-spacing': ['error', { beforeColon: false, afterColon: true }],
      'dot-notation': ['error', { allowKeywords: true }],
      'no-useless-rename': 'error',
      'prefer-rest-params': 'error',
      'object-shorthand': ['error', 'always'],
      'prefer-arrow-callback': 'error',
      'arrow-spacing': 'error',
      'rest-spread-spacing': ['error', 'never'],
      'yoda': ['error', 'never'],
      'no-nested-ternary': 'error',
      'no-unneeded-ternary': 'error',
      'prefer-object-spread': 'error',
      'no-duplicate-case': 'error',
      'no-fallthrough': 'error',
      'require-atomic-updates': 'off',
    },
  },
  {
    ignores: ['node_modules/**', 'dist/**', 'build/**', '.wrangler/**', 'coverage/**', 'src/__tests__/fixtures/**'],
  },
];
